### ISSUE TITLE
GCHP integration tests failing for 14.3.0-alpha.6

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#2110]
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard/GCST

### Description of your issue or question

Integration tests for 14.3.0-alpha.6 and 14.3.0-alpha.7 failed for gchp_merra2_fullchem with the following error:

```
 Getting CH4 boundary conditions in GEOS-Chem from :NOAA_GMD_CH4
  --- Do chemistry now

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#1  0x986108 in __cldj_interface_mod_MOD_run_cloudj
        at /n/home05/msulprizio/IT/GCHP_14.3.0-alpha.8/CodeDir/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/cldj_interface_mod.F90:531
#2  0x6d6618 in __photolysis_mod_MOD_do_photolysis
        at /n/home05/msulprizio/IT/GCHP_14.3.0-alpha.8/CodeDir/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/photolysis_mod.F90:602
...
```

@lizziel wrote:

>Looks like the issue is setting the relative humidity column passed to cloud-J. It isn't initialized for all levels.
>The fix is to find this:

```
       ! Set cloud fraction from input meteorology field                                                                  
       CLDF(1:State_Grid%NZ) = State_Met%CLDF(I,J,1:State_Grid%NZ)
       CLDF(State_Grid%NZ+1) = CLDF(State_Grid%NZ)
```

>and add (removing other RRR settings later): 

```
       ! Set humidity from input meteorology field
       ! Convert relative humidity [unitless] from percent to fraction
       RRR(1:State_Grid%NZ) = State_Met%RH(I,J,1:State_Grid%NZ) / 100.d0
       RRR(State_Grid%NZ+1) = RRR(State_Grid%NZ) * 1.d-1
```

**Comment by msulprizio** [comment]
This is resolved by #2111 which has been merged into the 14.3.0 development branch.
